#cloud-config
write_files:
  - owner: root:root
    path: /etc/test.txt
    defer: true
    content: |
      hello world
runcmd:
  - echo "========== START OF CUSTOM CLOUD-INIT =========="
  - swapoff -a
  - apt-get update
  - echo overlay | sudo tee -a /etc/modules-load.d/containerd.conf
  - echo br_netfilter | sudo tee -a /etc/modules-load.d/containerd.conf
  - echo "net.bridge.bridge-nf-call-ip6tables = 1" | sudo tee -a /etc/sysctl.d/kubernetes.conf
  - echo "net.bridge.bridge-nf-call-iptables = 1" | sudo tee -a /etc/sysctl.d/kubernetes.conf
  - echo "net.ipv4.ip_forward = 1" | sudo tee -a /etc/sysctl.d/kubernetes.conf
  - sysctl --system
  - apt install -y ca-certificates apt-transport-https ca-certificates curl gpg
  - install -m 0755 -d /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  - 'echo "Types: deb\nURIs: https://download.docker.com/linux/ubuntu\nSuites: $(. /etc/os-release && echo ${UBUNTU_CODENAME:-$VERSION_CODENAME})\nComponents: stable\nArchitecture: $(dpkg --print-architecture)\nSigned-by: /etc/apt/keyrings/docker.gpg" | tee /etc/apt/sources.list.d/docker.sources'
  - apt-get update
  - apt install -y containerd.io
  - containerd config default | tee /etc/containerd/config.toml
  - sed -i 's/SystemdCgroup \= false/SystemdCgroup \= true/g' /etc/containerd/config.toml
  - systemctl restart containerd
  - systemctl enable containerd
  - curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.35/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  - echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.35/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
  - apt update
  - apt install -y kubelet kubeadm kubectl
  - apt-mark hold kubelet kubeadm kubectl
  - echo "========== END OF CUSTOM CLOUD-INIT =========="

