---
apiVersion: v1
kind: Pod
metadata:
  name: helper
spec:
  containers:
  - name: helper
    image: mdimonte/helper:v0.1
    command:
      - "sleep"
      - "36000"
    resources:
      requests:
        cpu: 10m
        memory: 25Mi
      limits:
        cpu: 50m
        memory: 50Mi
  restartPolicy: Never
  terminationGracePeriodSeconds: 1
  automountServiceAccountToken: false
  